### ISSUE TITLE
Hrti error when attempting to run the addon

### ISSUE THREAD

**Issue by plapic** [nirvana-7777/plugin.video.hrti#13]
According to the log:
Error Contents: 'Common' object has no attribute 'resources'
Error Type: <class 'AttributeError'>
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/main.p line 60, in <module>

Running Kodi 20.2 on FireTV 4K Max

**Comment by plapic** [comment]
It appears this addon doesnt work on Android. Get the same error on Galaxy Tab S7FE.
Works fine in Windows 10.

**Comment by plapic** [comment]
2024-01-14 10:53:00.479 T:29520   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'Common' object has no attribute 'resources'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/main.py", line 60, in <module>
                                                       device_id = plugin.uniq_id()
                                                                   ^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/lib/common.py", line 190, in uniq_id
                                                       self.dialog_ok(self.get_resource('error_4005_ConnectionLost').get('text'))
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/lib/common.py", line 127, in get_resource
                                                       data = self.get_cache(self.resources)
                                                                             ^^^^^^^^^^^^^^
                                                   AttributeError: 'Common' object has no attribute 'resources'
                                                   -->End of Python script error report<--
                                                   
2024-01-14 10:53:00.561 T:29519   error <general>: GetDirectory - Error getting plugin://plugin.video.hrti/
2024-01-14 10:53:00.568 T:29442   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hrti/) failed

**Comment by plapic** [comment]
> It appears this addon doesnt work on Android. Get the same error on Galaxy Tab S7FE. Works fine in Windows 10.

Managed to get it working on a Sony Android TV. It took at few attempts to overcome the error messages. However standard Android on Samsung devices and Amazon Fire TV it will not work as it gives the same 'Common' object has no attribute 'resources' error at line 60 of main.py in the log

**Comment by kkumer** [comment]
I get the same error *'Common' object has no attribute 'resources'" on Kodi 20 and Kodi 21 on Apple TV 4k (tvOS 18.2) and the plugin will not run :-(   (This is very disappointing for me since this was my last option for running HRTi on this otherwise excellent hardware.)
